//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.03 at 07:39:02 PM TRT 
//


package com.frkn.invoicelister.ws;

import com.frkn.invoicelister.ws.model.WSRequest;
import com.frkn.invoicelister.ws.validation.AddCustomerValidation;
import com.frkn.invoicelister.ws.validation.WSValidation;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name"
})
@XmlRootElement(name = "addCustomerRequest")
public class AddCustomerRequest implements WSRequest {

    @XmlElement(required = true)
    protected String name;


    public String getName() {
        return name;
    }


    public void setName(String value) {
        this.name = value;
    }

    @Override
    public WSValidation getValidationModel() {
        return new AddCustomerValidation(this);
    }
}
