//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.03 at 07:39:02 PM TRT 
//


package com.frkn.invoicelister.ws;

import com.frkn.invoicelister.ws.model.WSRequest;
import com.frkn.invoicelister.ws.validation.AddInvoiceValidation;
import com.frkn.invoicelister.ws.validation.WSValidation;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invoicedate",
    "price",
    "customerId"
})
@XmlRootElement(name = "addInvoiceRequest")
public class AddInvoiceRequest implements WSRequest {

    @XmlElement(required = true)
    protected XMLGregorianCalendar invoicedate;

    @XmlElement(required = true)
    protected Double price;

    @XmlElement(required = true)
    protected Long customerId;

    public XMLGregorianCalendar getInvoicedate() {
        return invoicedate;
    }

    public void setInvoicedate(XMLGregorianCalendar invoicedate) {
        this.invoicedate = invoicedate;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    @Override
    public WSValidation getValidationModel() {
        return new AddInvoiceValidation(this);
    }
}
