//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.11.03 at 07:39:02 PM TRT 
//


package com.frkn.invoicelister.ws;

import javax.persistence.*;
import javax.xml.bind.annotation.*;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;


/**
 * <p>Java class for invoice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="invoice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="invoicedate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="cutomer" type="{http://www.frkn.com/invoicedata/ws}customer"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invoice")
@Entity
@Table(name = "Invoice")

public class Invoice {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "invoice_generator")
    @SequenceGenerator(name = "invoice_generator", sequenceName = "invoice_seq", allocationSize = 1)
    @Column(name = "id")
    private long id;

    //For the hibernate mapping
    @Column(name = "invoicedate")
    @XmlTransient
    private LocalDateTime invoicedateDb;

    //For the WebService
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    @Transient
    private XMLGregorianCalendar invoicedate;

    @XmlElement(required = true)
    @Transient
    private Customer customer;

    private double price;

    @XmlTransient
    @Column(name = "customer_id")
    private Long customerId;
    public Invoice() {
    }

    public Invoice(LocalDateTime invoicedateDb, XMLGregorianCalendar invoicedate, Customer customer, double price, Long customerId) {
        this.invoicedateDb = invoicedateDb;
        this.invoicedate = invoicedate;
        this.customer = customer;
        this.price = price;
        this.customerId = customerId;
    }

    public Invoice(LocalDateTime invoicedateDb, Customer customer, double price, Long customerId) {
        this.invoicedateDb = invoicedateDb;
        this.customer = customer;
        this.price = price;
        this.customerId = customerId;
    }

    public Invoice(LocalDateTime invoicedateDb, double price, Long customerId) {
        this.invoicedateDb = invoicedateDb;
        this.price = price;
        this.customerId = customerId;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the invoicedate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public LocalDateTime getInvoicedateDb() {
        return invoicedateDb;
    }

    /**
     * Sets the value of the invoicedate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */

    public void setInvoicedateDb(LocalDateTime value) {
        this.invoicedateDb = value;
    }

    /**
     * Gets the value of the cutomer property.
     * 
     * @return
     *     possible object is
     *     {@link Customer }
     *     
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the cutomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Customer }
     *     
     */
    public void setCustomer(Customer value) {
        this.customer = value;
    }

    /**
     * Gets the value of the price property.
     * 
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     */
    public void setPrice(double value) {
        this.price = value;
    }

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public XMLGregorianCalendar getInvoicedate() {
        return invoicedate;
    }

    @PostLoad
    public void setInvoicedate() {
        try {
            XMLGregorianCalendar invoiceDateAsXMLGregorianCalender =
                    DatatypeFactory.newInstance().newXMLGregorianCalendar(
                            this.invoicedateDb.format(DateTimeFormatter.ISO_LOCAL_DATE_TIME));
            this.invoicedate = invoiceDateAsXMLGregorianCalender;
        } catch (DatatypeConfigurationException e) {
            throw new RuntimeException(e);
        }
    }
}
